# Generated by Django 2.2.7 on 2019-11-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='artile',
            new_name='article',
        ),
    ]
